---
- name: Configure Localhost Demo
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  vars:
    demo_dir: "/tmp/spacelift-demo"
    
  tasks:
    - name: Debug all environment variables
      debug:
        msg: "{{ ansible_env }}"
      
    - name: Check specific variables from Terraform
      debug:
        msg: 
          - "target_hosts env var: {{ ansible_env.target_hosts | default('NOT_FOUND') }}"
          - "app_config env var: {{ ansible_env.app_config | default('NOT_FOUND') }}"
          - "deployment_timestamp env var: {{ ansible_env.deployment_timestamp | default('NOT_FOUND') }}"

    - name: Display received configuration
      debug:
        msg: 
          - "Configuring host: {{ inventory_hostname }}"
          - "Received variables from Spacelift dependency"
    
    - name: Create demo directory
      file:
        path: "{{ demo_dir }}"
        state: directory
        mode: '0755'
    
    - name: Create configuration file with received data
      copy:
        content: |
          # Spacelift Demo Configuration
          Target Hosts: {{ ansible_env.target_hosts | default('not-received') }}
          App Config: {{ ansible_env.app_config | default('not-received') }}
          Deployment Timestamp: {{ ansible_env.deployment_timestamp | default('not-received') }}
          Configured At: {{ ansible_date_time.iso8601 }}
          Target Host: {{ inventory_hostname }}
          OS Family: {{ ansible_os_family }}
          Python Version: {{ ansible_python_version }}
        dest: "{{ demo_dir }}/config.txt"
        mode: '0644'
    
    - name: Create success marker
      copy:
        content: |
          SUCCESS: Ansible configuration completed via Stack Dependencies v2
          Timestamp: {{ ansible_date_time.iso8601 }}
          Host: {{ inventory_hostname }}
          Spacelift Demo Complete
        dest: "{{ demo_dir }}/ansible-success.txt"
        mode: '0644'
    
    - name: Display completion message
      debug:
        msg: 
          - "Configuration completed successfully!"
          - "Check {{ demo_dir }}/ for created files"
          - "Target: {{ inventory_hostname }}"
          - "Spacelift Stack Dependencies v2 workflow complete"